version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: payflow-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: akash12@
      POSTGRES_DB: payflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: payflow-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:akash12@@db:5432/payflow?schema=public"
      PORT: 3000
      COOKIE_SECRET: "super-secret-cookie-signing-key-32-chars-long"
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: payflow-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

volumes:
  pgdata:
